github.com:
    users:
        banji007:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: banji007
